### ISSUE TITLE
[방 추가 페이지] 에러 상황 핸들링

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#144]
에러 상황에서 alert를 하는 것이 맞을까요???
관련 논의가 필요할 듯 합니다.

_Originally posted by @14KGun in https://github.com/sparcs-kaist/taxi-front/pull/135#discussion_r914847452_

**Comment by GrasshopperBears** [comment]
개인적으로는 alert보다는 별도 에러 페이지를 만드는 게 더 좋을 것 같습니다.
