### ISSUE TITLE
Global state 도입

### ISSUE THREAD

**Issue by GrasshopperBears** [sparcs-kaist/taxi-front#188]
# Summary 

현재 전역 상태가 없어 비효율적인 부분들이 많습니다. 예를 들어:
- user id
- location
- style 변수
이 있습니다. Global state를 도입해 비효율적인 코드를 개선할 수 있도록 합니다.

이 이슈에서는 상태 관리 라이브러리를 도입하고 location 관련 코드를 개선합니다. style 등의 변수는 별도 이슈에서 처리합니다.

# Tasks 

- [ ] 상태관리 라이브러리 조사 및 선정
- [ ] location을 전역 상태로 관리하도록 코드 개선

**Comment by GrasshopperBears** [comment]
참고자료

- https://frontendmastery.com/posts/the-new-wave-of-react-state-management/

**Comment by GrasshopperBears** [comment]
- re-rendering을 크게 감소
- `useState`와 비슷한 인터페이스를 사용해 다른 개발자들도 쉽게 익힐 수 있음

위와 같은 이유로 jotai를 상태 관리 라이브러리로 사용하려 합니다. 어떻게 생각하시나요? @14KGun @withSang @UrWrstNightmare

**Comment by UrWrstNightmare** [comment]
Jotai를 사용해 봤는데 너무 자유도가 높아서 오히려 사용하기 불편한 점이 있더라구요... 그리고 온라인에 자료가 많지 않은 점도 마이너스라 생각합니다 ㅠㅠ

그래서 제 개인 프로젝트에서는 recoil을 사용하고 있는데 어떤가요?

**Comment by GrasshopperBears** [comment]
자료는 확실히 recoil이 많은 것 같습니다. 자유도가 높은 게 장점이라 생각했는데 또 너무 높아도 쓰기 어려운 면이 있죠.... 저는 Recoil도 좋다고 생각합니다!

**Comment by 14KGun** [comment]
recoil도 useState와 유사하게 쓸 수 있어, 저도 recoil 또한 좋다고 생각합니다!

**Comment by withSang** [comment]
recoil 좋은 것 같아요!! Jotai 너무 마이너해요 ㅎㅎ

**Comment by GrasshopperBears** [comment]
시작하기
- https://abangpa1ace.tistory.com/212

recoil 프로젝트 구조
- https://wes-rast.medium.com/recoil-project-structure-best-practices-79e74a475caa
