### ISSUE TITLE
Making test examples

### ISSUE THREAD

**Issue by michellekjs** [sparcs-kaist/taxi-front#20]
In this issue, I want to create a test example for making a new issue.

**Comment by hyeongjunCho** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-04-13T15:12:33
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] Making test examples (#20)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
