### ISSUE TITLE
[Bug] 채널톡 상담시 아이디가 sso id로 설정되는 문제

### ISSUE THREAD

**Issue by GrasshopperBears** [sparcs-kaist/taxi-front#212]
# Describe the bug

채널톡 상담시 아이디가 sso id로 보여집니다.

# Screenshots

보안상의 이유로 사진을 첨부하지 않습니다. 채널톡 상담 참고 바랍니다.

**Comment by GrasshopperBears** [comment]
@14KGun @withSang userSchema의 `id`값으로 설정해서 생긴 문제입니다. 가능한 변경 옵션으로는

- `name`값으로 설정
  - 이 경우 `/json/logininfo/detail` API에 `name`값 추가가 필요합니다 (현재 없음)
- `subinfo`값으로 설정
  - 이 경우 포탈 로그인 유저는 학번이 표시되는 문제 있음

어떤 방식이 나을까요?

\+ 추가적으로 현재 백엔드 `transUserData` 함수에서 `name: userData.first_name + userData.last_name` 다음과 같이 설정해 부자연스러운 느낌이 있는 것 같아요 (`진우이`로 표시됨). 순서를 바꾸거나 가운데 띄어쓰기가 포함되면 좋을 것 같습니다.

**Comment by 14KGun** [comment]
저는 `name`이 적절해 보이는데, 
name은 `/json/logininfo` API에서 가져올 수 있습니다.
아마... 사용을 한다면.. 새로운 global state에 추가를 해야겠죠..??
@GrasshopperBears @withSang

**Comment by GrasshopperBears** [comment]
nickname, email 등의 정보도 필요해서 `Skeleton`에서 `/json/logininfo/detail` API를 호출하고 있는데, 여기서 같이 반환되면 좋을 것 같아서요! 안그러면 API를 두 번 호출해야 합니다...
