### ISSUE TITLE
common/modal 컴포넌트 뒤에서 스크롤 막기

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#269]
# Summary 

모달 컴포넌트가 띄어져 있을 때,
모달 뒤에서 스크롤이 되는 것을 막습니다.

**Comment by imYourChoi** [comment]
https://github.com/sparcs-kaist/taxi-front/blob/a0823ec5d17fe2cd539de74c7c906c7fdd558dab/src/components/common/roomOptions/Place.jsx#L23-L29

저는 이렇게 막았었습니다! 이슈 맡게된 분이 더 깔끔한 방법이 있는지 찾아봐주시면 감사하겠습니다!
