### ISSUE TITLE
"모든 방 검색하기" 버튼 "빠른 출발 검색"으로 수정

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#274]
## "모든 방 검색하기" 네이밍 이슈
모든 방 검색하기를 눌러도 24시간 이내의 방이 검색되는 것으로 알고 있습니다. 사용자들에게 혼란을 줄 수 있을 것 같습니다.

## 논의 결과
버튼을 "빠른 출발 검색"으로 수정합니다

_Originally posted by @14KGun in https://github.com/sparcs-kaist/taxi-front/discussions/219#discussioncomment-3569623_

**Comment by imYourChoi** [comment]
툴팁을 넣어 24시간 내의 결과가 나온다는 안내가 있어야 할 것 같습니다
