### ISSUE TITLE
[Bug] 커스텀 alert가 모달보다 뒤에 위치함

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#279]
# Describe the bug
커스텀 alert가 모달보다 뒤에 위치합니다.
아마, zIndex가 잘못 설정되어 있을 것이라고 추측됩니다.

# To Reproduce
1. 네비게이션바에서 마이페이지로 이동
2. 내 정보 수정 클릭
3. 프로필 사진 변경
4. Alert가 모달 창 뒤에 위치하는 것을 볼 수 있음

# Screenshots
<img src="https://user-images.githubusercontent.com/69258815/194504573-c82ec72f-8830-4686-948f-d9edfa2e3b5f.png">

**Comment by imYourChoi** [comment]
안그래도 확인해서 수정 예정입니다~
