### ISSUE TITLE
Hover 이벤트 통일

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#286]
# Summary 
#215 에서 버튼 배경색 문제가 제기되었습니다.
2022/09/06 회의 논의에 따라 모바일에서 hover 효과를 제거합니다.
모바일 여부는 `tools/isMobile` 에서 확인할 수 있습니다.

# To Do
코드 상 모든 hover 이벤트에 대하여
```
import isMobile from "tools/isMobile";

onMouseEnter={() => setHover(!isMobile)}
onMouseLeave={() => setHover(false)}
``` 
와 같이 수정합니다.

# Tasks
 - [ ] `isMobile`을 `package.json` 및 `tools` 에서 제거
 - [ ] 모든 컴포넌트의 touch hover 이벤트 통일

# 관련 논의 기록
- #215, #225
- 2022/09/06 회의
- https://github.com/sparcs-kaist/taxi-front/pull/276#discussion_r990542102

**Comment by 14KGun** [comment]
#276 에서 모바일 hover를 다시 살리는 것이 어떠하냐는 의견이 제시되었습니다.

_Originally posted by @imYourChoi in https://github.com/sparcs-kaist/taxi-front/pull/276#discussion_r990588973

**Comment by 14KGun** [comment]
```
// tools/hoverEventSets.js
const hoverEventSets = (setHover) => {
  return {
    onMouseEnter: () => setHover(true),
    onTouchStart: () => setHover(true),
    onMouseLeave: () => setHover(false),
    onTouchEnd: () => setHover(false),
    onTouchCancel: () => setHover(false),
  }
}

// components.js
...
const [isHover, setHover] = useState(false);
<div { ...hoverEventSets(setHover) } />
...
```

@imYourChoi, @GrasshopperBears  이런 구조 어떠신가요?

**Comment by GrasshopperBears** [comment]
예술이네요...

**Comment by imYourChoi** [comment]
https://github.com/sparcs-kaist/taxi-front/blob/2a9c22a747253f451c1bd3c1daf674e177395f07/src/components/common/Button.tsx#L83-L92

@14KGun 현재 `Button`에서는 hover와 clicked 이벤트를 모두 다루고 있어 추가해줘야 할것 같습니다. 또한 모바일에서 hover와 clicked 중 어떤 상태를 사용할지 디자인이 확실하지 않아서 그 부분 일단 정하고 작업해야 할 것 같습니다.
