### ISSUE TITLE
마이페이지/프로필 수정에서 별명 Enter로 수정 가능

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#290]
# Summary

마이페이지/프로필 수정에서 별명을 엔터를 눌러 수정 가능하도록 합니다.

<center>
<img width="300" alt="스크린샷 2022-10-17 오후 10 16 38" src="https://user-images.githubusercontent.com/69258815/196186887-0983e0dc-c1dd-49b7-af1d-646096dddc4e.png">
</center>

- 별명에서 텍스트 수정 후 "수정하기" 버튼 클릭 뿐만 아니라 엔터로도 수정할 수 있도록 합니다

_Originally posted by @14KGun in https://github.com/sparcs-kaist/taxi-front/pull/278#discussion_r996397923_

**Comment by GrasshopperBears** [comment]
그럼 모바일에서도 동일한가요?

**Comment by 14KGun** [comment]
> 그럼 모바일에서도 동일한가요?

@GrasshopperBears 저는 모바일이랑 PC 구분 없이 엔터로 별명을 수정 가능할 수 있도록 하면 편할 것이라고 생각했는데,
모바일 환경에서의 다른 의견이 있으신가요??
