### ISSUE TITLE
RLayout으로 감싸는 여부 Type 통일

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#333]
# Summary

`marginAuto`는 `R1`으로 감싸는 여부이고 `R2`는 `R2`로 감싸는 여부인 것 같은데, prop 이름이 서로 다르네요
global type으로 `wrapFromR` (작명 대충 함, 이름 추천 받아요) `"R1" | "R2" | null` 정의해서 두 prop 통일하는 것 어떠신가요?
추후에 다른 common 컴포넌트들도 이 타입으로 통일시키고요

_Originally posted by @14KGun in https://github.com/sparcs-kaist/taxi-front/pull/316#discussion_r1011038237_

오 좋은 것 같아요. 이왕 말 나온 김에 이슈 파서 RLayout 관련 이름들도 다시 짓는것 어떤가요? R1이랑 R2 뭔가 직관적이지 않고 useReactiveState가 반환하는 값도 1,2,3보단 더 나은 이름이 있을것 같아요

_Originally posted by @imYourChoi in https://github.com/sparcs-kaist/taxi-front/pull/316#discussion_r1011109829_

**Comment by 14KGun** [comment]
@imYourChoi @0ev 

`RLayout` 명칭 수정을

`<AdaptiveDiv type="center">{children}</AdaptiveDiv>`

`<AdaptiveDiv type="butterfly" left={children1} right={children2} />`

`<AdaptiveDiv type="modal">{children}</AdaptiveDiv>`

어떤가요???

**Comment by imYourChoi** [comment]
좋은 것 같습니다~~
