### ISSUE TITLE
[Bug] 내 방 리스트 "방을 선택하세요"

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#338]
# Describe the bug
내 방 리스트 PC 화면에서 "방을 선택하세요" 문구가 `common/Empty` 컴포넌트로 감싸져 있는 것 같지 않습니다.

# To Reproduce
1. 내 방 리스트 페이지로 이동합니다.

# Screenshots
<img src="https://user-images.githubusercontent.com/69258815/199867332-a3a37e81-7be2-4f09-8ecd-8638c4137b96.png">

**Comment by imYourChoi** [comment]
이 부분은 지금 있는 PR들 머지되면 사라질 이슈입니다. 방을 선택하지 않았을 때 오른쪽 UI가 아예 뜨지 않을 예정입니다.
