### ISSUE TITLE
[Bug] 기본 프로필에서 프로필 사진 변경

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#339]
# Describe the bug
프로필 이미지가 기본 이미지일 때, 마이 페이지에서 프로필 사진 변경이 바로 반영되지 않습니다.

# To Reproduce
1. 마이 페이지로 이동
2. "기본 이미지 일 때" 프로필 사진을 변경
3. 사진 변경에 성공하였다는 모달이 뜨나, 브라우저에서는 변경된 사진이 보이지 않음
4. 그러나 새로고침하면, 변경된 프로필 이미지를 확인할 수 있음
5. (기본 프로필)에서 프로필 변경을 하였을 때만 이러한 버그가 있는 것 처럼 보임

# Screenshots
프로필 이미지 수정을 하였으나.... 수정된 이미지가 보이지 않음
<img src="https://user-images.githubusercontent.com/69258815/199868397-9c8a9dab-7281-4d6f-a57d-0f1143f283a7.png">

**Comment by imYourChoi** [comment]
저도 확인했습니다! 근데 한번 바꾸고 난 뒤에는 다시 재현해볼 수가 없어 원인을 모르겠네요
