### ISSUE TITLE
[Bug] 방 개설에서 시간 또는 분이 0인 시간, 개설 불가능

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#340]
# Describe the bug
방 개설에서 시간 또는 분이 0일 때 방 개설이 불가능합니다.

# To Reproduce
1. 방 개설 페이지로 이동
2. 시간 또는 분을 0으로 설정
3. 다른 개설 옵션들을 선택
4. 방 개설 버튼에서 "시간을 선택해 주세요"라는 메시지와 함께 버튼 클릭이 막혀있음을 확인할 수 있음

# Screenshots
<img src="https://user-images.githubusercontent.com/69258815/199869014-44ebf62b-9777-4d10-8d2e-1a3a7d3fc4e0.png" width="300">

**Comment by imYourChoi** [comment]
이 부분은 방 개설 조건문만 고치면 바로 해결할수 있을 것 같습니다
