### ISSUE TITLE
[Bug] 내 방 리스트 SideChat 띄어놓은 후 다른 페이지로의 이동 불가

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#341]
# Describe the bug
내 방 리스트 PC화면 페이지에서 SideChat을 띄어 놓으면 다른 페이지로의 이동이 불가능해집니다.

# To Reproduce
1. 내 방 리스트로 이동
2. 참여 중인 방 아무 방 클릭 후, SideChat 활성화
3. 네비게이션 바에서 다른 페이지로의 이동 시도
4. 페이지 이동이 불가능해짐을 확인할 수 있음

# Screenshots
1. SideChat 활성화한 후

<img src="https://user-images.githubusercontent.com/69258815/199869948-635948fb-0f94-44fe-9d77-9502302499be.png">

2. 네비게이션 바에서 버튼 클릭한 후

<img src="https://user-images.githubusercontent.com/69258815/199869991-3e798b2a-b338-4177-b41b-2c7ac669f6ec.png">

**Comment by imYourChoi** [comment]
지금 main에 Navigation 버튼의 Link에 있는 to가 `{"/" + props.page}`가 아닌 `{props.page}`로 되어 있어서 그렇습니다.
