### ISSUE TITLE
[Bug] 모바일에서 스크롤 문제

### ISSUE THREAD

**Issue by GrasshopperBears** [sparcs-kaist/taxi-front#346]
# Describe the bug

장소 스크롤에서 빈 옵션이 선택됩니다

# To Reproduce
1. 출발지 터치
2. 위로 스크롤
3. 빈 공간이 선택됨

# Screenshots

![KakaoTalk_20221104_135031321](https://user-images.githubusercontent.com/34625313/199890360-7f587864-7674-426c-815a-8fa8383a28e5.jpg)

**Comment by imYourChoi** [comment]
아 이거 큰 문제네요.. 저도 방금 사용해봤는데 picker의 전체적인 사용성이 굉장히 별로네요... 다른 라이브러리를 찾아볼까요

**Comment by GrasshopperBears** [comment]
https://www.npmjs.com/package/react-mobile-picker-scroll
이런 것도 있구요

**Comment by imYourChoi** [comment]
@GrasshopperBears 
첫번째 솔루션 테스트해봤는데 우선 리액트 버전이 안맞네요. 따로 클론해서 사용해봤을 때는 모바일에서는 괜찮을거 같은데 컴퓨터에서는 트랙패드로는 스크롤 방향이 반대라 애매하네요
두번째는 스크롤 했을 때 고정이 안되고 선택도 안돼서 조금 이상할거 같아요
