### ISSUE TITLE
[Bug] 아이폰 주소 창 숨겨졌을 때 모달 창 스크롤 오류

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#356]
# Describe the bug
아이폰 사파리에서 주소 창이 숨겨졌을 때 모달 창위에서 스크롤을 하면 배경이 움직임

# To Reproduce
1. 아이폰으로 접속
2. 아래로 스크롤하여 주소창을 숨김
3. `장소`나 `시간`을 클릭하여 모달 창을 염
4. 스크롤 시에 배경이 움직임

# Screenshots

https://user-images.githubusercontent.com/84715637/200173128-105b7b05-ad8f-415e-aff1-095f0be3ed77.MP4

**Comment by GrasshopperBears** [comment]
참고 링크: https://stackoverflow.com/a/24727206
