### ISSUE TITLE
PopupProvider로 팝업 관리

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#372]
# Summary 

팝업이 필요한 곳에서 팝업을 띄우기보다 AlertProvider처럼 하나로 관리

# Tasks 

- [ ] TBD...

**Comment by 14KGun** [comment]
`PopupProvider`는 fixed 컴포넌트가 nested로 사용되면서 생긴 stacking context로 인한 모달 zIndex 문제를 해결할 수 있습니다.

## 버그 예시 이미지

<div>

<img src="https://user-images.githubusercontent.com/69258815/227943424-043ffbcf-956e-4fe1-a51e-8cf297f87923.png" width="400">

<img src="https://user-images.githubusercontent.com/69258815/227943434-3b94d89c-c217-41ec-b8eb-fe9076fe11a8.png" width="400">


</div>

**Comment by imYourChoi** [comment]
@14KGun https://slash.page/ko/libraries/react/use-overlay/src/useoverlay.i18n/ 참고가 될것 같아 가져와봤습니다!

**Comment by 14KGun** [comment]
@imYourChoi `ModalProvider`를 커스텀하게 만든다면 일단 global state를 { `isOpen`, `onChangeIsOpen`, `children` }로 구성이 이뤄지도록 만들고 컴포넌트 구현 내부는 `AlertProvider`와  비슷하게 만들면 될 것 같았는데 대충 `OverlayProvider`와 비슷한 것 같아요. 다만 여러 개의 Overlay를 만들 수 있다는 점이 저희 `AlertProvider`와 비교해서 `useOverlay`의 장점인 것 같습니다.

도입 혹은 구성 참고 확인해 보겠습니다 !! 😄 😄
