### ISSUE TITLE
[Bug] 닉네임 수정 모달 닫힘

### ISSUE THREAD

**Issue by GrasshopperBears** [sparcs-kaist/taxi-front#382]
# Describe the bug

닉네임 수정시 모달이 의도치 않게 닫힘

# To Reproduce
1. 닉네임 수정 모달 띄움
2. 닉네임 input에서 드래그 시작
3. dimmed 영역에서 드래그 끝냄
4. 모달이 닫혀버림

**Comment by imYourChoi** [comment]
이건 사실 버그라기보다는 onClick의 발생 순서에 다른 제스쳐로 저희가 어떤 제스쳐를 용인하느냐의 차이인 것 같습니다. 실제로 웹버전 유튜브 쇼츠의 댓글 창도 이러한 제스쳐가 발생하는 것으로 확인했습니다.
