### ISSUE TITLE
로그아웃 시 리다이렉트 주소 변경

### ISSUE THREAD

**Issue by happycastle114** [sparcs-kaist/taxi-front#392]
# Summary 

앱에서 로그아웃 감지를 위해 로그아웃 시 리다이렉트 하는 주소의 링크를
/login => /logout으로 변경합니다.

로그인이 되지 않았을 경우 어떤 path로 접속하든 로그인 페이지로 연결되므로
사용상 큰 차이가 없을 것으로 예상됩니다..!

# Tasks 

- [x] 로그인 리다이렉트 링크 변경

**Comment by 14KGun** [comment]
@happycastle114 로그아웃 페이지로 이동함을 감지하는 것이 아니라
클라이언트가 현재 로그인 페이지에 있으면 로그아웃되어 있는 것 아닌가요???

**Comment by happycastle114** [comment]
> @happycastle114 로그아웃 페이지로 이동함을 감지하는 것이 아니라 클라이언트가 현재 로그인 페이지에 있으면 로그아웃되어 있는 것 아닌가요???

@14KGun 클라이언트가 로그인 페이지로 가게 되는 시나리오가 2가지 입니다!

1. 로그아웃을 클릭하여 로그인을 풀었을 경우 => 이 경우에는 저장되어있는 토큰을 삭제하고 기기 토큰을 DB에서 제거해야합니다.

2. 세션 시간이 만료되어 로그아웃 되었을 경우 => 이 경우에는 토큰을 사용하여 세션을 발급받고 발급받은 세션을 이용하여 다시 로그인을 진행해야합니다( 사용자 다시 로그인 불필요 )
Ex) KLMS 앱 => KLMS 앱에서 세션 만료로 로그인이 풀렸을 경우 klms 웹사이트의 로그인 페이지로 가게 되지만, 앱을 재접속하게 되면 바이오로그인으로 로그인할 수 있음.

두 가지 케이스를 구분하기 위해 1번 케이스의 경우 /logout 으로 먼저 이동 후 앱에서 /logout 링크로 들어갔음을 감지하고 앱 자체의 자동로그인 화면을 띄웁니다.

**Comment by happycastle114** [comment]
정확하게는 로그아웃 버튼을 클릭하였는지 확인하는 것입니다!

**Comment by 14KGun** [comment]
@happycastle114 좋은 방법인 것 같습니다 !!  👍 

다만 `Skeleton` 컴포넌트에서 `/logout` url에서 에러페이지 띄운 상태에서 `logininfo` api 호출해서 로그아웃을 감지하는 것 같아서..
약간의 꼼수 같습니다 ㅋㅋㅋㅋㅋ

개선 방안 회의 때 논의해 봐요
