### ISSUE TITLE
[Bug] 채팅 날짜 바뀔시 넘어감

### ISSUE THREAD

**Issue by imYourChoi** [sparcs-kaist/taxi-front#395]
# Describe the bug
한 사람이 전날 마지막 채팅을 치고 그 다음날 첫 채팅을 치면 전날의 채팅이 다음날로 넘어옴.
(인준이의 화면만 봤고 재연은 아직 안해봄)

# To Reproduce

# Screenshots

**Comment by GrasshopperBears** [comment]
### 재연
![bug](https://user-images.githubusercontent.com/34625313/204005085-df5b3845-df9a-4911-8bfe-acdb333904b3.gif)
