### ISSUE TITLE
베타 안내창 지우기

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#409]
# Summary 

정식 버전 출시 전에 베타 안내창이 띄어지지 않도록 안내창을 지웁니다.

[베타 안내창 이슈](https://github.com/sparcs-kaist/taxi-front/issues/365)

**Comment by imYourChoi** [comment]
@14KGun 저희 베타 안내문 자체는 코드에 남겨둘건가요?

**Comment by 14KGun** [comment]
지우기 이까운데, 스켈레톤에서 주석으로 감쌀까요?

**Comment by imYourChoi** [comment]
저희 나중에 뭐 기능 업데이트 하면 띄운다거나 설문 조사, 공유 이벤트 등등 쓸곳은 많을것 같아서 그냥 주석 처리만 해둬도 괜찮을거 같아요
