### ISSUE TITLE
[Bug] 요일별 출발하는 방

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#416]
# Describe the bug (1)

홈 페이지 첫 화면에서 오늘 날짜가 아닌 하루 전 날짜가 뜸

<img width="476" alt="스크린샷 2022-11-29 오전 12 11 05" src="https://user-images.githubusercontent.com/69258815/204312457-7971053f-fcc4-4055-9591-04a30398585a.png">

# Describe the bug (2)

전체 버튼 선택 시 아무 것도 안뜸..

<img width="449" alt="스크린샷 2022-11-28 오후 11 57 48" src="https://user-images.githubusercontent.com/69258815/204309348-11780ad8-5713-4042-b923-f3d5e1b16b74.png">

**Comment by imYourChoi** [comment]
@14KGun 아직 유효한가요?

**Comment by 14KGun** [comment]
이슈 닫겠습니다 ~ @imYourChoi
