### ISSUE TITLE
Top notification bar 추가하기

### ISSUE THREAD

**Issue by 0ev** [sparcs-kaist/taxi-front#597]
# Summary 

<img src="https://github.com/sparcs-kaist/taxi-front/assets/63383967/e78bfa4b-f883-4861-84fe-b71c0e74e879" width=300>

모바일 디바이스로 서비스 접근 시, 택시 앱 설치 상단 바를 띄웁니다.

# Tasks 

- [ ] 컴포넌트 제작
- [ ] 컴포넌트 위치
- [ ] 완성

**Comment by 14KGun** [comment]
예뻐요 ~~ ❤️

**Comment by 14KGun** [comment]
https://github.com/sparcs-kaist/taxi-front/issues/545 과 이슈가 겹치는 것 같아요
