### ISSUE TITLE
[Bug] .heic 이미지 업로드 하면 깨짐

### ISSUE THREAD

**Issue by 0ev** [sparcs-kaist/taxi-front#610]
# Describe the bug
.heic 이미지 업로드 하면 이미지가 깨집니다.
컴퓨터에서 heic이미지를 업로드 해야만 나오는 버그이기 때문에 중요도는 매우 낮습니다.
# To Reproduce
1. upload a heic image to chatting

# Screenshots
![image](https://github.com/sparcs-kaist/taxi-front/assets/63383967/38355555-2d98-42b4-b0f9-9775db4d7ab9)
![image](https://github.com/sparcs-kaist/taxi-front/assets/63383967/2fd696c0-6a52-4fb9-b3cf-44709f50ef14)

**Comment by 0ev** [comment]
아름답네요

**Comment by withSang** [comment]
https://github.com/alexcorvi/heic2any/issues/42
이 이슈로 보입니다.
heic2any 버전을 0.0.3에서 0.0.4로 올리면 해결된대요!
