### ISSUE TITLE
이벤트 시작 후 긴급사항 수정

### ISSUE THREAD

**Issue by 0ev** [sparcs-kaist/taxi-front#673]

**Comment by 14KGun** [comment]
1. 상점 모달 버튼 단어단위 쪼개기 -> 송편이 부족합니다. 로 텍스트 수정
2. 모든 이벤트 페이지 뒤로가기 버튼 눌렀을 때, 홈으로 가도록
3. 엔제리너스 문구 변경 (슬랙 내용 확인)
4. 랜덤박스 열어도 인스타그램 모달 띄우기
