### ISSUE TITLE
"수정 완료" or "수정 하기"

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-front#79]
피그마의 My page 에서,
"수정 완료" 버튼이 "수정 하기"로 변경되어 적절할 것 같습니다.

**Comment by 14KGun** [comment]
그리고 nickname 입력 최대 길이를 정해야 할 것 같습니다

**Comment by imYourChoi** [comment]
> 그리고 nickname 입력 최대 길이를 정해야 할 것 같습니다

최대 12글자가 적당할 것 같습니다

**Comment by hyeongjunCho** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-04-26T22:11:48
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] "수정 완료" or "수정 하기" (Issue #79)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
