### ISSUE TITLE
[Chatting] 채팅방 컴포넌트화 및 내 방 리스트 페이지 우측에 적용

### ISSUE THREAD

**Issue by T-dubb** [sparcs-kaist/taxi-front#91]
1. 채팅방 컴포넌트화
2.  내 방 리스트 페이지 우측에 적용

**Comment by hyeongjunCho** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-04-26T22:48:51
          
          
            * 메일 제목 : 
[sparcs-kaist/taxi-front] [Chatting] 채팅방 컴포넌트화 및 내 방 리스트 페이지 우측에 적용 (Issue #91)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
