### ISSUE TITLE
[Chatting] 채팅창의 내용이 보이지 않음

### ISSUE THREAD

**Issue by 0ev** [sparcs-kaist/taxi-front#93]
채팅창의 내용을 볼 수 있게 만들기

**Comment by hyeongjunCho** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-05-03T00:41:48
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] [Chatting] 채팅창의 내용이 보이지 않음 (Issue #93)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
