### ISSUE TITLE
출발지/도착지 피커에서 터치 스크롤 시 오류 발생

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/taxi-front#96]
1. 재현 방법
- 모바일 환경에서 검색 페이지에 접속하거나 데스크톱에서 [개발자 옵션]-[장치 에뮬레이션 토글]을 활성화한 뒤, 출발지/도착지 피커에서 터치로 스크롤을 할 때마다 `Unable to preventDefault inside passive event listener invocation.` 오류가 발생합니다.
2. 원인
- 터치 스크롤 관련 이벤트들을 처리하기 위해서는(`"onTouchStart"`, `"onTouchMove"`, `"onWheel"` 등) 패시브 이벤트 리스너를 사용해야 하는데, 패시프 이벤트 리스너에서는 기존 이벤트 리스너와 다르게 preventDefault를 호출할 수 없습니다.
- Reference: https://www.uriports.com/blog/easy-fix-for-unable-to-preventdefault-inside-passive-event-listener/
3. 해결책
- 터치 스크롤 관련 이벤트들에서 preventDefault를 호출하지 않도록 패치된 react-mobile-picker를 사용하면 됩니다. ( https://github.com/adcentury/react-mobile-picker/commit/cc19eb51495797c4f49fcb4b4a424665e1fd3f61 )

**Comment by hyeongjunCho** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-04-27T01:36:09
          
          
            * 메일 제목 : 
[sparcs-kaist/taxi-front] [Search] 출발지/도착지 피커에서 터치 스크롤 시 오류 발생 (Issue #96)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by withSang** [comment]
해당 라이브러리도 여전히 해결이 되지 않은 걸로 보여요 ㅠㅠ 소스 코드만 바뀌어서 새로 라이브러리 빌드 해야겠어요

**Comment by hyeongjunCho** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-04-27T23:41:15
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] [Search] 출발지/도착지 피커에서 터치 스크롤 시 오류 발생 (Issue #96)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
